# This file was partly generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage
import subprocess

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / r"assets\frame0"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


cookie = ""
check = True
uncheck = False
force = False
verbose = False

window = Tk()

window.geometry("919x482")
window.configure(bg="#2A2A2A")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_image_2_on = PhotoImage(
    file=relative_to_assets("button_2_on.png"))
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_image_3_on = PhotoImage(
    file=relative_to_assets("button_3_on.png"))
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_image_4_on = PhotoImage(
    file=relative_to_assets("button_4_on.png"))


def invert_check():
    global check
    check = not check
    button_2.config(image=button_image_2_on if check else button_image_2)


def invert_uncheck():
    global uncheck
    uncheck = not uncheck
    button_3.config(image=button_image_3_on if uncheck else button_image_3)


def invert_force():
    global force
    force = not force
    button_4.config(image=button_image_4_on if force else button_image_4)


def start_scanning():
    global cookie
    cookie = entry_1.get().strip()
    command = "main.py"
    if cookie != "":
        command += f' --cookie "{cookie}"'
    if check:
        command += " -c"
    if uncheck:
        command += " -u"
    if force:
        command += " -fd"
    subprocess.Popen(command, shell=True)


canvas = Canvas(
    window,
    bg="#2A2A2A",
    height=482,
    width=919,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_text(
    233.0,
    20.0,
    anchor="nw",
    text="HSR Achievement Scanner",
    fill="#FFFFFF",
    font=("Segoe UI Light", 36 * -1)
)

canvas.create_text(
    16.0,
    75.0,
    anchor="nw",
    text="Cookie: ",
    fill="#FFFFFF",
    font=("Segoe UI Light", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    500.0,
    89.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#3B3B3B",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Segoe UI Light", 24 * -1)
)
entry_1.place(
    x=107.0,
    y=72.0,
    width=786.0,
    height=32.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=start_scanning,
    relief="flat"
)
button_1.place(
    x=340.0,
    y=419.0,
    width=239.0,
    height=43.0
)

button_2 = Button(
    image=button_image_2_on if check else button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=invert_check,
    relief="flat"
)
button_2.place(
    x=336.0,
    y=133.0,
    width=239.0,
    height=43.0
)

button_3 = Button(
    image=button_image_3_on if uncheck else button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=invert_uncheck,
    relief="flat"
)
button_3.place(
    x=654.0,
    y=133.0,
    width=239.0,
    height=43.0
)

button_4 = Button(
    image=button_image_4_on if force else button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=invert_force,
    relief="flat"
)
button_4.place(
    x=18.0,
    y=133.0,
    width=239.0,
    height=43.0
)

canvas.create_text(
    17.0,
    187.0,
    anchor="nw",
    text="Activate on first use.\nDownloads the list of \nachievements.",
    fill="#FFFFFF",
    font=("Segoe UI Light", 24 * -1)
)

canvas.create_text(
    322.0,
    187.0,
    anchor="nw",
    text="Check the achievements\non StarDB. Needs the\ncookie to be set.",
    fill="#FFFFFF",
    font=("Segoe UI Light", 24 * -1)
)

canvas.create_text(
    654.0,
    187.0,
    anchor="nw",
    text="Uncheck visible\nachievements\non StarDB. Needs the\ncookie to be set",
    fill="#FFFFFF",
    font=("Segoe UI Light", 24 * -1)
)

canvas.create_text(
    16.0,
    314.0,
    anchor="nw",
    text="Open the achievements menu and click on the first tab before scanning. To stop\nthe scan, press Alt+Tab. "
         "While scanning, DO NOT MOVE/CLICK YOUR MOUSE\nOR PRESS A KEY THE KEYBOARD or the the scanner will go wild.",
    fill="#FFFFFF",
    font=("Segoe UI Light", 24 * -1)
)

window.resizable(False, False)
window.mainloop()
